PRAGMA journal_mode=WAL;

CREATE TABLE IF NOT EXISTS olts (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  hostname TEXT NOT NULL,
  ip TEXT NOT NULL UNIQUE,
  community TEXT NOT NULL,
  vendor TEXT NOT NULL DEFAULT 'bdcom',
  last_refresh_at DATETIME NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS ponports (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  olt_ip TEXT NOT NULL,
  ifindex TEXT NOT NULL,
  name TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS gpon (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  olt_ip TEXT NOT NULL,
  portonu TEXT NOT NULL,
  idonu TEXT NOT NULL,
  snonu TEXT NOT NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS gpon_uq ON gpon(olt_ip, portonu, idonu);

CREATE TABLE IF NOT EXISTS onu_notes (
  sn_norm TEXT PRIMARY KEY,
  note TEXT NOT NULL DEFAULT '',
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS onu_seen (
  sn_norm TEXT PRIMARY KEY,
  first_seen TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  last_seen TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  last_online TIMESTAMP NULL,
  status INTEGER NULL
);

CREATE TABLE IF NOT EXISTS recent_new_onu (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  sn_norm TEXT NOT NULL UNIQUE,
  first_seen TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  olt_ip TEXT NOT NULL,
  portonu TEXT NOT NULL,
  idonu TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_gpon_sn_norm ON gpon(REPLACE(UPPER(snonu),' ',''));
CREATE INDEX IF NOT EXISTS idx_gpon_olt_ip ON gpon(olt_ip);
CREATE INDEX IF NOT EXISTS idx_ponports_olt_if ON ponports(olt_ip, ifindex);
CREATE INDEX IF NOT EXISTS idx_recent_new_onu_first_seen ON recent_new_onu(first_seen DESC);
